FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY worker/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY worker /app/worker
COPY norms.yaml /app/norms.yaml
COPY critical_norms.yaml /app/critical_norms.yaml
COPY pattern_1С.yaml /app/pattern_1С.yaml
COPY docs/system_standards.txt /app/docs/system_standards.txt

CMD ["python", "-m", "worker.app.main"]
